apiVersion: v1
kind: Namespace
metadata:
  name: atlas
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: space-controller
  namespace: atlas
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: atlas:controller:spacecontroller
rules:
- apiGroups:
  - ""
  - "spacecontroller.seizadi.github.com"
  resources:
  - services
  - pods
  - secrets
  - spaces
  - events
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: atlas:controller:space-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: atlas:controller:spacecontroller
subjects:
- kind: ServiceAccount
  name: space-controller
  namespace: atlas
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: space-controller
  namespace: atlas
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: space-controller
    spec:
      serviceAccountName: space-controller
      containers:
      - name: space-controller
        image: soheileizadi/space-controller:latest
        imagePullPolicy: Always
