apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: spaces.spacecontroller.seizadi.github.com
spec:
  group: spacecontroller.seizadi.github.com
  version: v1alpha1
  names:
    kind: Space
    plural: spaces
  scope: Namespaced
  subresources:
    status: {}
