apiVersion: v1
kind: Namespace
metadata:
  name: contacts-app-seizadi-minikube-dev
---
apiVersion: spacecontroller.seizadi.github.com/v1alpha1

kind: Space
metadata:
  name: seizadi-v1-0-contacts-app
  namespace: contacts-app-seizadi-minikube-dev
spec:
  secretName: contacts-app-seizadi-minikube-dev-secrets
  path: k8s
  secrets:
    # echo -n 'postgres' | base64
    # echo -n 'cG9zdGdyZXM=' | base64 --decode; echo
    ATLAS_DATABASE_PASSWORD:  cG9zdGdyZXM=
